services:
  postgres:
    image: postgres:16-alpine
    container_name: gila_postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: gila
      POSTGRES_PASSWORD: gila123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: gila_mongo
    environment:
      MONGO_INITDB_DATABASE: ecommerce_logs
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:    
  mongo_data:
